### ISSUE TITLE
OAuth callback loop

### ISSUE THREAD

**Issue by wilsonminer** [newsdev/driveshaft#15]
Running Driveshaft from Heroku, and set up OAuth with Google. Accepting the OAuth permissions redirects back to the Driveshaft callback and then immediately triggers the request dialog again. Assuming I have something misconfigured, but can't pinpoint where.

**Comment by abstrctn** [comment]
Hi @wilsonminer, sorry about the trouble! I've been debugging this morning, and my best guess is that this is cropping up from a call to the Google+ API [here](https://github.com/newsdev/driveshaft/blob/v0.1.1/lib/driveshaft/auth.rb#L124). It isn't enabled for new Google Projects by default, and I mistakenly omitted it from the docs.

Could you try adding `Google+ API` to the list of authorized APIs in your google project? (https://console.developers.google.com/project/YOUR-APP-ID/apiui/apiview/plus/overview)

If that doesn't solve it, can you post the list of environmental variables that you have defined, and/or the result of running `heroku logs -a HEROKU-APP-ID` if you have the [Heroku CLI](https://devcenter.heroku.com/articles/heroku-command) installed?

**Comment by wilsonminer** [comment]
Thanks for the response!

I didn't have the Google+ API enabled, but turning it on didn't seem to have any effect. Here are the Heroku logs, you can see the oauthcallback requests at the end: http://d.pr/f/1huGN

Excepting the basic Driveshaft and S3 settings (which were working with public documents before I tried adding the auth settings), I have `DRIVESHAFT_SETTINGS_AUTH_REQUIRED` set to false (I'm testing the auth by clicking "sign in" so I can still use the app while I figure it out) and I have both GOOGLE_APICLIENT_CLIENTSECRETS_WEB and GOOGLE_APICLIENT_SERVICEACCOUNT set. I added the service account method to get the non-public spreadsheets working without the oauth token.

**Comment by abstrctn** [comment]
Hi @wilsonminer, thanks the logs are really useful!

It looks like the OAuth callback is redirecting to Driveshaft using the route `/oauth2callback`, which is the default redirect path that Google sets up for new OAuth credentials. However, Driveshaft actually expects to receive Google's OAuth response at `/auth/callback`; when it receives a request at `/oauth2callback`, it thinks you're trying to access a file and begins the OAuth loop again.

Try the following:

1. Log in to [Google Developers Console](https://console.developers.google.com), and go to the project you set up for Driveshaft
2. Navigate to **APIs & auth** > **Credentials**
3. Under your **Client ID for web application** credentials, click on **Edit settings**
4. Under **Authorized redirect URIs**, change any occurrences of `oauth2callback` to `auth/callback`. An example of what it should look like: `https://lit-reaches-1568.herokuapp.com/auth/authorize`
5. Update the `GOOGLE_APICLIENT_CLIENTSECRETS_WEB` environmental variable in Heroku with the new credential JSON

Let me know if that works!

It might be worth silently redirecting `/oauth2callback` to `/auth/callback` internally to prevent this in the future.

**Comment by wilsonminer** [comment]
That did it! Definitely missed that in the setup docs. Thanks for the thorough explanation.
